version: '3'

services:
  proxy:
    build: ./Proxy
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - frontend

  frontend:
    build: ./FrontEnd
    restart: always
    # ports:
    #   - 8080:80
    depends_on:
      - backend
  
  backend:
    build: ./BackEnd
    restart: always
    # ports:
    #   - 5050:5050
    depends_on:
      - database

  database:
    image: mongo
    restart: always
    # ports:
    #   - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root