version: '3'

services:
  frontend:
    build: ./FrontEnd
    restart: always
    ports:
      - 8080:80
  
  backend:
    build: ./BackEnd
    restart: always
    ports:
      - 5050:5050

  # database:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: root